globalThis.answers = {

	// https://www.wizard101.com/quiz/trivia/game/wizard101-zafaria-trivia

  "Belloq is first found in:": "The Sook",
  "The Fire Lion Ravagers are led by:": "Nergal the Burned Lion",
  "Who is not one of the Zebu Kings:": "Zaffe Zoffer",
  "Unathi Nightrunner is:": "A councilor of Baobab",
  "Zebu Blackstripes legendary blade was called:": "The Sword of the Duelist",
  "Zebu Blackstripes legendary blade was forged:": "In the halls of Valencia",
  "Inyanga calls Umlio a:": "Fire feather",
  "Esop Thornpaw gives you a magic:": "Djembe Drum",
  "Koyate Ghostmane accuses the player of:": "Being a thief",
  "Zamunda's great assassin is known as:": "Karl the Jackal",
  "The Inzinzebu Bandits are harassing the good merchants in:": "Baobab Market",
  "Baobab is governed by:": "A Council of three councilors.",
  "Rasik Pridefall is:": "An Olyphant from Stone Town",
  "Jambo means:": "Hello.",
  "Umlilo Sunchaser hired who as a local guide?:": "Msizi Redband",
  "Sir Reginal Baxby's cousin is:": "Mondli Greenhoof",
  "What does Lethu Blunthoof says about Ghostmanes?": "You never can tell with them!",
  "Who are Hannibal Onetusk's brother and co-pilot?": "Mago and Sobaka",
  "Who is the missing prince?": "Tiziri Silvertusk",
  "Vir Goodheart is an assistant to:": "Rasik Pridefall",

  // https://www.wizard101.com/quiz/trivia/game/wizard101-wizard-city-trivia

  "Who sang the Dragons, Tritons and Giants into existance?": "Bartleby",
  "What is Diego's full name?": "Diego Santiago Quariquez Ramirez the Third",
  "What are the main colors for the Myth School?": "Blue and Gold",
  "Who resides in the Hedge Maze?": "Lady Oriel",
  "What is the name of the Ice Tree in Ravenwood?": "Kelvin",
  "What is Mindy's last name (she's on Colossus Blvd)?": "Pixiecrown",
  "Who is the Fire School professor?": "Dalia Falmea",
  "What school does Malorn Ashthorn think is the best?": "Death",
  "Who taught Life Magic before Moolinda Wu?": "Sylvia Drake",
  "What is the gemstone for Balance?": "Citrine",
  "Who is the Wizard City mill foreman?": "Sohomer Sunblade",
  "What is something that the Gobblers are NOT stockpiling in Colossus Way?": "Broccoli",
  "What are the school colors of Balance?": "Tan and Maroon",
  "What does every Rotting Fodder in the Dark Caves carry with them?": "A spade",
  "What is the name of the bridge in front of the Cave to Nightside?": "Rainbow Bridge",
  "What is the name of the grandfather tree?": "Bartleby",
  "What is the name of the school newspaper? Boris Tallstaff knows...": "Ravenwood Bulletin",
  "What school is all about Creativity?": "Storm",
  "Where is Sabrina Greenstar?": "Fairegrounds",
  "Who is the Princess of the Seraphs?": "Lady Oriel",

  // https://www.wizard101.com/quiz/trivia/game/wizard101-spells-trivia

  "How many pips does it cost to cast Stormzilla?": "5",
  "What does Forsaken Banshee do?": "375 damage plus a hex trap",
  "Mildred Farseer teaches you what kind of spell?": "Dispels",
  "Who can teach you the Life Shield Spell?": "Sabrina Greenstar",
  "Which Fire spell both damages and heals over time?": "Power Link",
  "What isn't a shadow magic spell?": "Ebon Ribbons",
  "What level of spell does Enya Firemoon Teach?": "80",
  "Ether Shield protects against what?": "Life and Death attacks",
  "Which spell would not be very effective when going for the elixir vitae Badge?": "Entangle",
  "Tish'Mah specializes in spells that mostly affect these:": "Minions",
  "What type of spells are Ice, Fire, and Storm?": "Elemental",
  "Mortis can teach you this.": "Tranquilize",
  "What term best fits Sun Magic Spells?": "Enchantment",
  "If you're a storm wizard with 4 power pips and 3 regular pips, how powerful would your supercharge charm be?": "110%",
  "Which spell can't be cast while polymorphed as a Gobbler?": "Pie in the sky",
  "Cassie the Ponycorn teaches this kind of spell:": "Prism",
  "How many pips does it cost to cast Dr. Von's Monster?": "9",
  "If you can cast Storm Trap, Wild Bolt, Catalan, and the Tempest spell, what are you polymorphed as?": "Ptera",
  "What term best fits Star Magic Spells?": "Auras",
  "Who teaches you balance magic?": "Alhazred",
  "The Fire spell that damages and heals over time is": "Power Link",

  // https://www.wizard101.com/quiz/trivia/game/wizard101-spellbinding-trivia

  'Who tells you to speak these words only unto your mentor: "Meena Korio Jajuka!"': "Priya the Dryad",
  "Who grants the first Shadow Magic spell?": "Sophia DarkSide",
  'Who taunts you with: "Prepare to be broken, kid!"': "Clanker",
  "Morganthe got the Horned Crown from the Spriggan:": "Gisela",
  "Who needs the healing potion from Master Yip?": "Binh Hoa",
  "Who is Haraku Yip's apprentice?": "Binh Hoa",
  "What does Silenus name you once you've defeated Hades?": "Glorious Golden Archon",
  'Who tells you: "A shield is just as much a weapon as the sword."': "Mavra Flamewing",
  "Who taunts: Why I oughta knock you to the moon, you pesky little creep!": "Mugsy",
  "Sumner Fieldgold twice asks you to recover what for him?": "Shrubberies",
  "What special plant was Barley developing in his Garden?": "Cultivated Woodsmen",
  "Who tries to raise a Gorgon Army?": "Phorcys",
  "What badge do you earn by defeating 100 Samoorai?": "Yojimbo",
  "Where has Pharenor been imprisoned?": "Skythorn Tower",
  "Who makes the harpsichord for Shelus?": "Gretta Darkkettle",
  'Who taunts you with: "Wizard, you will know the meaning of the word pain after we battle!"': "Aiuchi",
  "In Azteca, Morganthe enlisted the help of the:": "The Black Sun Necromancers",
  "Who thinks you are there to take their precious feathers?": "Takeda Kanryu",
  "The Swallows of Caliburn migrate to Avalon from where each year?": "Zafaria and Marleybone",
  "Who helps Morganthe find the Horn of Huracan?": "Belloq",

  // https://www.wizard101.com/quiz/trivia/game/wizard101-mystical-trivia

  "Hrundle Fjord is part of what section of Grizzleheim?": "Wintertusk",
  "Who is the Emperor of Mooshu's Royal Guard?": "Noboru Akitame",
  "Who gives you permission to ride the boat to the Krokosphinx?": "Sergent Major Talbot",
  "What is used to travel to the Isle of Arachnis?": "Ice Archway",
  "King Neza is Zenzen Seven Star's:?": "Grandfather",
  "Who takes you across the River of Souls?": "Charon",
  "In Reagent's Square, the Professor is standing in front of a:": "Telegraph Box",
  "Who did Falynn Greensleeves fall in love with?": "Sir Malick de Logres",
  "Where is the only pure fire in the Spiral found?": "Wizard City",
  "Who asks you to find Khrysanthemums?": "Eloise Merryweather",
  "King Axaya Knifemoon needs what to unify the people around him?": "The Badge of Leadership",
  "Who was ordered to guard the Sword of Kings?": "The Knights of the Silver Rose",
  "Who is the only person who knows how to enter the Tomb of Storms?": "Hetch Al'Dim",
  "Which villain terrorizes the fair maidens of Marleybone?": "Jaques the Scatcher",
  "In what world would you find the Spider Temple": "Zafaria",
  "Thaddeus Price is the Pigswick Academy Professor of what school?": "Tempest",
  "Who was the greatest Aquilan Gladiator of all time? Answer:": "Dimachaerus",
  "What was Ponce de Gibbon looking for in Azteca?": "The Water of Life",
  "Who haunts the Night Warren?": "Nosferabbit",
  "Who tells you how to get to Aquila?": "Harold Argleston",
  "Vir Goodheart is an assistant to:": "Rasik Pridefall",
  "Rasik Pridefall is:": "An Olyphant from Stone Town.",
  "Who are Hannibal Onetusk's brother and co-pilot?": "Mago and Sobaka",
  "Inyanga calls Umlio a:": "Fire feather",
  "Baobab is governed by:": "A Council of three councilors.",
  "Unathi Nightrunner is:": "A councilor of Baobab.",
  "Umlilo Sunchaser hired who as a local guide?": "Msizi Redband",
  "Belloq is first found in:": "The Sook",
  "Zebu Blackstripes legendary blade was called:": "The Sword of the Duelist",
  "What was Ponce de Gibbon looking for in Azteca?": "The Water of Life",
  "Who was ordered to guard the Sword of Kings?": "The Knights of the Silver Rose",
  "Who tells you how to get to Aquila?": "Harold Argleston",
  "In Reagent's Square, the Professor is standing in front of a:": "Telegraph Box",
  "Who is the Emperor of Mooshu's Royal Guard?": "Noboru Akitame",
  "King Axaya Knifemoon needs what to unify the people around him?": "The Badge of Leadership",
  "Who takes you across the River of Souls?": "Charon",
  "Where is the only pure fire in the Spiral found?": "Wizard City",
  "Who did Falynn Greensleeves fall in love with?": "Sir Malick de Logres",
  "Which villain terrorizes the fair maidens of Marleybone?": "Jaques the Scatcher",
  "What is used to travel to the Isle of Arachnis?": "Ice Archway",
  "Who haunts the Night Warrens?": "Nosferabbit",

  // https://www.wizard101.com/quiz/trivia/game/wizard101-marleybone-trivia

  "What sort of beverage is served in Air Dales Hideaway?": "Root Beer",
  "What time of day is it always in Marleybone?": "Night",
  "What color are the Marleybone mailboxes?": "Red",
  "Which is not a street in Regent's Square?": "Fleabitten Ave",
  "Which symbol is not on the stained glass window in Regent's Square?": "A Tennis Ball",
  "What event is Abigail Doolittle sending out invitations for?": "Policeman's Ball",
  "What did Prospector Zeke lose in Marleybone?": "The Stray Cats",
  "What is Sgt. Major Talbot's full name?": "Sylvester Quimby Talbot III",
  "What course did Herold Digmoore study?": "Ancient Myths for Parliament",
  "What initials were on the doctor's glove?": "XX",
  "What is a very common last name of the cats in Marleybone?": "O'Leary",
  "What style of artifacts are in the Royal Museum?": "Krokotopian",
  "What two names are on the Statues in the Marleybone cathedral?": "Saint Bernard and Saint Hubert",
  "Arthur Wethersfield is a:": "Dog",
  "Who is not an officer you'll find around Marleybone?": "Officer Digmore",
  "Who is the dangerous criminal that is locked up, but escapes from Newgate Prison?": "Meowiarty",
  "What transports you from place to place in Marleybone?": "Hot Air Balloons",
  "What time does the clock always read in Marleybone?": "1:55",
  "What is flying around in Regent's Square?": "Newspapers",
  "Which of these folks can you find in the Royal Museum?": "Clancy Pembroke",

  // "https://www.wizard101.com/quiz/trivia/game/wizard101-magical-trivia"

  "Who is the Registrar of Pigswick Academy?": "Mrs. Dowager",
  "Who guards the entrance to Unicorn Way?": "Private Stillson",
  "How many worlds of The Spiral are unlocked as of May 21st, 2014?": "12",
  "What is the shape of the pink piece in potion motion?": "Heart",
  "What can be used to diminish the Nirini's powers in Krokotopia?": "Flame Gems",
  "What color is the door inside the boys dormroom?": "Red",
  "What's the name of the balance tree?": "Niles",
  "Who prophesizes this? “The mirror will break, The horn will call, From the shadows I strike , And the skies will fall”.": "Morganthe",
  "Why are the pixies and faeries on Unicorn Way evil?": "Rattlebones corrupted them.",
  "Zafaria is home to what cultures?": "Gorillas, Zebras, Lions",
  "Which one of these are not a symbol on the battle sigil?": "Wand",
  "Who sells Valentine's Day items in Wizard City?": "Valentina Heartsong",
  "What is the name of the book floating around the Wizard City library?": "Basic Wizarding & Proper Care of Familiars",
  "What book does Professor Drake send you to the library to check out?": "Book on the Wumpus",
  "Who is the Nameless Knight?": "Sir Malory",
  "Which is the only school left standing in Dragonspyre?": "Fire",
  "Merle Ambrose is originally from which world?": "Avalon",
  "What did Prospector Zeke lose track of in MooShu?": "Blue Oysters",
  "Which below are NOT a type of Oni in MooShu?": "Ruby",
  "Why are the Gobblers so afraid to go home?": "Witches",
  "Which of these locations is not in Wizard City?": "Digmore Station",
  "How many worlds of The Spiral are unlocked as of May 21st, 2014?": "12",
  "Who prophesizes this? “The mirror will break, The horn will call, From the shadows I strike , And the skies will fall…”": "Morganthe",
  "What is the title of the book that is FLOATING around the Wizard City LIBRARY?": "Basic Wizarding & Proper Care of Familiars",

  // "https://www.wizard101.com/quiz/trivia/game/wizard101-conjuring-trivia"

  "What was the name of the powerful Grendel Shaman who sealed the runic doors?": "Thulinn",
  "Who is the King of the Burrowers?": "Pyat MourningSword",
  "What did Abigail Dolittle accuse Wadsworth of stealing?": "Genuine Imitation Golden Ruby",
  "What book was Anna Flameright accused of stealing?": "Advanced Flameology",
  "Who Is NOT a member of the Council of Light?": "Cyrus Drake",
  "Kirby Longspear was once a student of which school of magic?": "Death",
  "Sir Edward Halley is the Spiral's most famous:": "Aztecosaurologist",
  "Who is Bill Tanner's sister?": "Sarah Tanner",
  "What level must you be to wear Dragonspyre crafted clothing?": "33",
  "How many portal summoning candles are in the Burial Mound?": "Three",
  "What is the shape on the weather vanes in the Shopping District?": "Half moon/moon",
  "Which Queen is mentioned in the Marleybone book “The Golden Age”?": "Ellen",
  "The Swordsman Destreza was killed by:": "A Gorgon",

  // "https://www.wizard101.com/quiz/trivia/game/wizard101-adventuring-trivia"

  "In Grizzleheim, the Ravens want to bring about:": "The Everwinter, to cover the world in ice",
  "Who is in the top level of the Tower of the Helephant?": "Lyon Lorestriker",
  "How long do you have to wait to join a new match after fleeing in PVP?": "5 minutes",
  "What determines the colors of the manders in Krok?": "Where they come from and their school of focus",
  "What is the name of the new dance added with Khrysalis?": "The bee dance",
  "What is unique about Falmea's Classroom?": "There are scorch marks on the ceiling",
  "What is Professor Falmea's favorite food?": "Pasta Arribata",
  "Which of these are not a lore spell?": "Fire Dragon",
  "What is the name of the book stolen from the Royal Museum?": "The Krokonomicon",
  "What school is the Gurtok Demon focused on?": "Balance",
  "What school is the spell Dark Nova?": "Shadow",
  "What does the Time Ribbon Protect against?": "Time Flux",
  "What type of rank 8 spell is granted to Death students at level 58?": "Damage + DoT",
  "What hand does Lady Oriel hold her wand in?": "Trick question, she has a sword",
  "Shaka Zebu is known best as:": "The Greatest Living Zebra Warrior",
  "Which Aztecan ponders the Great Questions of Life?": "Philosoraptor",
  "Which of these is NOT a Zafaria Anchor Stone?": "Rasik Anchor Stone",
  "Who is the Bear King of Grizzleheim?": "Valgard Goldenblade",
  "An unmodified Sun Serpent does what?": "900 - 1000 Fire Damage + 300 Fire Damage to entire team",
  "What is the name of the secret society in Krokotopia": "Order of the Fang",

  // "https://www.wizard101.com/quiz/trivia/game/pirate101-valencia-trivia"

  "Who reads the inscription on Marleybone's Tower?": "Ratbeard",
  "Where do you find the Tomb of Marco Pollo?": "Granchia",
  "What shows Steed you're part of the Resistence?": "Amulet",
  "Historian Gonzago is on a stage, who isn't in the audience?": "Giafra",
  "What are Albus and Carbo?": "Armada Commanders",
  "How many Mechanical Birds do you collect in Sivella?": "5",
  "Who do you find in the Lecture Hall of Sivella?": "Ridolfo",
  "Why does Steed want you to attack Armada Ships?": "Make a Disguise",
  "You won't find this kind of Armada Troop in Sivella!": "Battle Angel",
  "Historian Gonzago sends you on a “paper chase,” who do you talk to during that quest?": "Magdalena",
  "Which one isn't a Scholar by name?": "Lorenzo",
  "What color of Windstone do you find in Marco Pollo's Tomb?": "Blue",
  "Which one isn't a Scholar by name?": "Caresini",
  "Which world doesn't have a pillar in Sivella?": "Monquista",
  "What type of item does Prospector Zeke want you to find in Valencia?": "Birds",
  "You need a good eye to save these in Granchia…": "Art Objects",
  "Who does Steed send you to speak to in Sivella?": "Thaddeus",
  "What's the name of a librarian in Sivella?": "Grassi",
  "The Mooshu Tower in Sivella is a replica of what?": "Tower of Serenity",
  "What type of boat do you use to get from the docks to Sivella?": "Gondola"
  
}